-- Fix: 199 advisors "function_search_path_mutable" en funciones de aplicación.
-- ALTER FUNCTION ... SET search_path TO 'public' es metadata-only (no toca body ni firma).
-- Funciones de extensión (pgvector, pg_trgm) están excluidas — se alterarían al actualizar la extensión.

ALTER FUNCTION public._norm_nombre(p text) SET search_path TO 'public';
ALTER FUNCTION public.abuelo_contact_name() SET search_path TO 'public';
ALTER FUNCTION public.cash_autorellenar_dia(p_fecha date) SET search_path TO 'public';
ALTER FUNCTION public.cash_stats_semanas(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.clientes_pref_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.clientes_programa_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.clientes_seguimiento_excluidos() SET search_path TO 'public';
ALTER FUNCTION public.clientes_seguimiento_semanal(p_dias_umbral integer, p_dias_activo integer) SET search_path TO 'public';
ALTER FUNCTION public.clientes_seguimiento_v2(p_dias_activo integer) SET search_path TO 'public';
ALTER FUNCTION public.cobros_backups_lista(p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.cobros_set_updated_at() SET search_path TO 'public';
ALTER FUNCTION public.crear_user_interno(p_email text, p_password text, p_role app_role) SET search_path TO 'public';
ALTER FUNCTION public.current_role() SET search_path TO 'public';
ALTER FUNCTION public.dashboard_briefing_get(p_fecha date) SET search_path TO 'public';
ALTER FUNCTION public.dashboard_briefing_historial(p_dias integer) SET search_path TO 'public';
ALTER FUNCTION public.dashboard_clientes_inactivos() SET search_path TO 'public';
ALTER FUNCTION public.dashboard_clientes_riesgo_fuga() SET search_path TO 'public';
ALTER FUNCTION public.dashboard_costes_subiendo(p_dias integer, p_pct_min numeric) SET search_path TO 'public';
ALTER FUNCTION public.dashboard_kpis_hoy() SET search_path TO 'public';
ALTER FUNCTION public.dashboard_kpis_serie(dias integer) SET search_path TO 'public';
ALTER FUNCTION public.dashboard_pendiente_mismatch() SET search_path TO 'public';
ALTER FUNCTION public.dashboard_productos_anomalos(p_dias integer) SET search_path TO 'public';
ALTER FUNCTION public.dashboard_pvp_sugerido(p_dias integer, p_pct_min numeric, p_margen_objetivo_pct numeric) SET search_path TO 'public';
ALTER FUNCTION public.dashboard_top_deudores() SET search_path TO 'public';
ALTER FUNCTION public.emit_audit_requested() SET search_path TO 'public';
ALTER FUNCTION public.emit_event(p_event_type text, p_payload jsonb, p_source text, p_priority text, p_correlation_id uuid) SET search_path TO 'public';
ALTER FUNCTION public.es_gestor_cobros() SET search_path TO 'public';
ALTER FUNCTION public.es_operaciones() SET search_path TO 'public';
ALTER FUNCTION public.es_responsable() SET search_path TO 'public';
ALTER FUNCTION public.ferlu_emit_caja_cierre_dia() SET search_path TO 'public';
ALTER FUNCTION public.ferlu_emit_cobros_deuda_alta() SET search_path TO 'public';
ALTER FUNCTION public.gastos_alertas_proximos_pagos() SET search_path TO 'public';
ALTER FUNCTION public.gastos_calendario_mes(p_anio integer, p_mes integer) SET search_path TO 'public';
ALTER FUNCTION public.gastos_fijos_pagos_detalle(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.gastos_resumen_periodo(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.gastos_serie_mensual(p_meses integer) SET search_path TO 'public';
ALTER FUNCTION public.gastos_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.is_admin() SET search_path TO 'public';
ALTER FUNCTION public.is_admin_full() SET search_path TO 'public';
ALTER FUNCTION public.manager_abuelo_borrar_espejo() SET search_path TO 'public';
ALTER FUNCTION public.manager_abuelo_factura_create(p_fecha date, p_numero_factura text, p_nota text, p_lineas jsonb) SET search_path TO 'public';
ALTER FUNCTION public.manager_catalogo_productos(p_q text, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_cliente_evolucion_mensual(p_contact_name_canon text, p_meses integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_cliente_facturas(p_contact_name_canon text, p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_cliente_heatmap_dia(p_contact_name_canon text, p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_cliente_margen_detalle(p_contact_name_canon text, p_from date, p_to date, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_cliente_productos(p_contact_name_canon text, p_from date, p_to date, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_clientes_lista(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_clientes_por_dia(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_factura_detalle(p_factura_id text) SET search_path TO 'public';
ALTER FUNCTION public.manager_facturas_delete(p_ids text[]) SET search_path TO 'public';
ALTER FUNCTION public.manager_facturas_lista(p_from date, p_to date, p_tipo text, p_subtipo text, p_q text, p_limit integer, p_offset integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_facturas_lista(p_from date, p_to date, p_tipo text, p_subtipo text, p_q text, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_forecast_proximo_mes() SET search_path TO 'public';
ALTER FUNCTION public.manager_heatmap_cliente_dia(p_from date, p_to date, p_top integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_mapa_clientes(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_patrones_dia_semana(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_pedidos_proximos() SET search_path TO 'public';
ALTER FUNCTION public.manager_producto_clientes(p_product_id text, p_from date, p_to date, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_producto_compras(p_product_id text, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_producto_historico(p_product_id text, p_meses integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_productos_lista(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_recomendaciones() SET search_path TO 'public';
ALTER FUNCTION public.manager_resumen_comparativo(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_resumen_periodo(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_serie_diaria(p_from date, p_to date) SET search_path TO 'public';
ALTER FUNCTION public.manager_top_clientes_margen(p_from date, p_to date, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.manager_top_productos_margen(p_from date, p_to date, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.memory_recall(p_tenant_id text, p_query_embedding vector, p_limit integer, p_categories text[], p_min_importance integer, p_min_score double precision) SET search_path TO 'public';
ALTER FUNCTION public.notif_emit(p_audience text, p_empleado_id uuid, p_tipo text, p_titulo text, p_cuerpo text, p_payload jsonb) SET search_path TO 'public';
ALTER FUNCTION public.notif_empleados_activos() SET search_path TO 'public';
ALTER FUNCTION public.notif_puntos_trigger() SET search_path TO 'public';
ALTER FUNCTION public.notif_push_dispatch_trigger() SET search_path TO 'public';
ALTER FUNCTION public.notif_snapshot_empleado(p_empleado_id uuid) SET search_path TO 'public';
ALTER FUNCTION public.notif_tareas_trigger() SET search_path TO 'public';
ALTER FUNCTION public.notif_vacaciones_trigger() SET search_path TO 'public';
ALTER FUNCTION public.notificaciones_listar() SET search_path TO 'public';
ALTER FUNCTION public.notificaciones_purgar_antiguas() SET search_path TO 'public';
ALTER FUNCTION public.notificaciones_push_after_insert() SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_buscar_productos_holded(p_query text, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_compras_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_confirmado_dispatch() SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_cotejo(p_fecha date) SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_productos_holded_touch() SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_productos_resumen() SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_recurrentes_generar(p_fecha date) SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_recurrentes_touch() SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_reordenar_ruta(p_fecha date, p_repartidor text, p_orden uuid[]) SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_resolver_completo(p_pedido_id uuid) SET search_path TO 'public';
ALTER FUNCTION public.pedidos_wa_sugerencias_mapeo() SET search_path TO 'public';
ALTER FUNCTION public.puede_operar_pedidos_wa() SET search_path TO 'public';
ALTER FUNCTION public.puede_ver_clientes() SET search_path TO 'public';
ALTER FUNCTION public.puede_ver_manager() SET search_path TO 'public';
ALTER FUNCTION public.push_subscription_delete(p_endpoint text) SET search_path TO 'public';
ALTER FUNCTION public.push_subscription_upsert(p_endpoint text, p_p256dh text, p_auth text, p_user_agent text) SET search_path TO 'public';
ALTER FUNCTION public.push_targets_para_notificacion(p_notif_id uuid) SET search_path TO 'public';
ALTER FUNCTION public.repartos_jornada_set_updated_at() SET search_path TO 'public';
ALTER FUNCTION public.ruleta_activa_set(p_activa boolean) SET search_path TO 'public';
ALTER FUNCTION public.ruleta_canjear_self(p_tiradas integer) SET search_path TO 'public';
ALTER FUNCTION public.ruleta_es_sabado_madrid(p_now timestamp with time zone) SET search_path TO 'public';
ALTER FUNCTION public.ruleta_is_activa() SET search_path TO 'public';
ALTER FUNCTION public.ruleta_marcar_entregado(p_tirada uuid, p_entregado boolean) SET search_path TO 'public';
ALTER FUNCTION public.ruleta_otorgar_tirada(p_empleado uuid, p_motivo text, p_cantidad integer) SET search_path TO 'public';
ALTER FUNCTION public.ruleta_resumen_admin() SET search_path TO 'public';
ALTER FUNCTION public.ruleta_saldo_self() SET search_path TO 'public';
ALTER FUNCTION public.ruleta_self_estado() SET search_path TO 'public';
ALTER FUNCTION public.ruleta_tirar() SET search_path TO 'public';
ALTER FUNCTION public.seguimiento_excluir(p_name text, p_motivo text) SET search_path TO 'public';
ALTER FUNCTION public.seguimiento_marcar_llamado(p_name text) SET search_path TO 'public';
ALTER FUNCTION public.seguimiento_restaurar(p_name text) SET search_path TO 'public';
ALTER FUNCTION public.tareas_completed_at_insert() SET search_path TO 'public';
ALTER FUNCTION public.tareas_completed_at_sync() SET search_path TO 'public';
ALTER FUNCTION public.touch_updated_at() SET search_path TO 'public';
ALTER FUNCTION public.trab_cond_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.trab_credito_recalcular_total() SET search_path TO 'public';
ALTER FUNCTION public.trab_fest_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.trab_he_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.trab_pts_a_euros(p_puntos integer) SET search_path TO 'public';
ALTER FUNCTION public.trab_pts_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.trab_ruleta_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.trab_vac_touch_updated() SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_colaboraciones_detalle_mes(p_empleado uuid, p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_colaboraciones_resumen_mes(p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_colaboraciones_self_mes(p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_credito_estado_actual() SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_credito_estado_mes(p_empleado_id uuid, p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_credito_factura_create(p_empleado_id uuid, p_fecha date, p_nota text, p_lineas jsonb) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_credito_historico(p_empleado_id uuid) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_festivos_lista_anio(p_anio integer) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_fichaje_abrir(p_lat double precision, p_lng double precision, p_nota text) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_fichaje_actual() SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_fichaje_admin_borrar(p_id uuid) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_fichaje_admin_crear(p_empleado_id uuid, p_ts_in timestamp with time zone, p_ts_out timestamp with time zone, p_nota text) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_fichaje_admin_editar(p_id uuid, p_ts_in timestamp with time zone, p_ts_out timestamp with time zone, p_nota text) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_fichaje_cerrar(p_lat double precision, p_lng double precision, p_nota text) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_fichajes_mes(p_empleado_id uuid, p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_fichajes_semana(p_lunes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_fichajes_touch() SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_horas_extras_lista_mes(p_mes date, p_empleado uuid) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_horas_extras_resumen_mes(p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_puntos_ajustes_mes(p_empleado_id uuid, p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_puntos_detalle_mes(p_empleado_id uuid, p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_puntos_dia(p_fecha date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_puntos_resumen_mes(p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_sabados_importar_turnos(p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_sabados_resumen_mes(p_mes date) SET search_path TO 'public';
ALTER FUNCTION public.trabajadores_vacaciones_resumen_anual(p_anio integer) SET search_path TO 'public';
